# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jonathan harper
description: "jonathan harper's website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "jonathanharper3.github.io" # the base hostname & protocol for your site
github_username:  jonathanharper3
#twitter_username: n/a
#email: jcharper@umich.edu
fakeemail: jcharper @ umich . edu
# Build settings
markdown: kramdown
officemaploc: "https://goo.gl/maps/GCuaU6Dqgm3SvsN67"
officeloc: 1 Main Street, SLC
include: ["_publications"]
collections:
  - publications
